### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by scriptxd** [xtekky/TikTok-View-Bot#2]
Only 100? Sometimes not working...
Not given properly 😔
Tooo slow....

**Comment by xtekky** [comment]
could you please give more details about the issue

**Comment by scriptxd** [comment]
Its stop working after given 500-1k
also not work after sleep period end....
In one day only 500-1k?
Only work one time in a day...
Maximum time data not loaded from server...
I didn't changed anything inside without VIDEO,IID,DID  ....
Fix please....

**Comment by xtekky** [comment]
yo this is the only mobile code working on GitHub and is a free version, it's meant to be used on pc but yh, I don't have enough time to update it
